### ISSUE TITLE
Hardcoded uname path incorrect on Ubuntu

### ISSUE THREAD

**Issue by dpdoughe** [wdebeaum/WebParser#1]
On Line 257 in parse-to-xml.lisp the uname call is hardcoded to 
/usr/bin/uname
, but on Ubuntu this path is
/bin/uname

Hot-patching the file to use /bin/uname fixes the issue, but wondering if there is more robust method in Lisp for checking existence of file or getting system information?

**Comment by wdebeaum** [comment]
The robust method is not to use Lisp ;)

I changed that command to `/bin/sh -c uname` in order to make use of the `$PATH` environment variable:

    (run-program-and-read-output "/bin/sh" "-c" "uname")

`/bin/sh` is much more likely to exist in that location across different platforms.
