### ISSUE TITLE
KQML.pm not loading

### ISSUE THREAD

**Issue by dpdoughe** [wdebeaum/WebParser#4]
The 
`use KQML` 

line in both drum and parse CGI scripts seemed to cause an error due to being unable to load the KQML.pm Perl module in the same folder (cgi).  Adding lines like:
```
require './KQML.pm';
KQML->import();
```
at the top of each script seemed to fix the issue.  FYI, I'm running Perl v5.22.1 for x86_64-linux-gnu-thread-multi

**Comment by wdebeaum** [comment]
I'm guessing your web server is running the perl CGI scripts in taint mode, which removes `'.'` from `@INC` (among other things), meaning it wouldn't load `KQML` from `./KQML.pm` without the path being explicitly given. I didn't know about removing `'.'`, and had thought our own web servers were also enabling taint mode, but I guess I was mistaken. So I added the `-T` option to the perl shebang lines to explicitly enable taint mode, and for `cgi-kqml-bridge.pl.in` I also added `-I.` to add `'.'` back to `@INC` so it can still `use KQML` normally. Even if taint mode wasn't the issue, `-I.` should still make `use KQML` work for you, so I'm closing the ticket.
